### PR TITLE
Updated Log In UI

### PR DESCRIPTION
**Pull request by vanshsoni**
Please merge asap so that I can do PR for register Page UI
and also for email validation on register Page
Reference #1

### CODE REVIEW

**Comment by opticod** [comment]
I had already merged Logged In UI from you at https://github.com/NJACKWinterOfCode/E-voting-portal/pull/13 . What are the changes you are targeting here? Share screenshot

**Comment by vanshsoni** [comment]
screenshot 150
Here it is 
Please check fast 
I have two more PR

**Comment by vanshsoni** [comment]
I have change UI of login Page

**Comment by vanshsoni** [comment]
and need to make PR for register page and email validation

**Comment by opticod** [comment]
Can you please say again what was the UI for https://github.com/NJACKWinterOfCode/E-voting-portal/pull/13 , the first screenshot or the second one ?

**Comment by opticod** [comment]
Don't wait for this PR getting merged, you can work in branches and create multiple PRs at the same time. Learn more about it here https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

**Comment by vanshsoni** [comment]
the first one 
I am making only one PR with all changes now

**Comment by opticod** [comment]
Ok, got it. Reviewing the final PR.

**Pull request closed without merging**
