### PR TITLE
materializecss added

### PR DESCRIPTION
**Pull request by bksahu**
In the header,php
1. Materialize.css stylesheet added 
2. Nav bar added
3. li updated

### CODE REVIEW

**Comment by opticod** [comment]
Can you please share the screenshot for the changed items ?

**Comment by bksahu** [comment]
Okay sure. But the problems is my web browser is not rendering .php files. So I have to change it .htm, work on it and then change it back to .php.

**Comment by bksahu** [comment]
Image There you go. 
I am facing problem as my browser is unable to render the .php files. So I have to convert them to .htm and work on it and then change it back. I am unable to run the project properly on my local machine.

**Comment by opticod** [comment]
For running the php code, you need Apache Server, you can know more about on how to install here http://php.net/manual/en/book.apache.php

**Comment by bksahu** [comment]
I have xampp already installed and also Apache comes by default on Ubuntu but still my browser is not able to render. I will try to fix it again. 
Anyway is that what you wanted ? Does my PR fulfill your requirements ?

**Comment by opticod** [comment]
Yes, please attach the screenshot of the complete home page after running. 

May be you haven't created the database in your server, with the mentioned tables from the README file. For easiness for all, you can create a database and also add its link in README file. 

Refer new issue of that: https://github.com/NJACKWinterOfCode/E-voting-portal/issues/5

**Comment by tameeshB** [comment]
@bksahu  You might have Apache server preinstalled but the php won't be rendered unless you point the browser to the localhost server directory. 
From the secreenshot, I see you are viewing the page from 'file://xyz' which is pointing to the server, you need to point to the server for it to render.
1) git clone the repository inside your server root(/var/www/html by default or look up in your apache config)
2) point the browser to localhost/{name of subfolder where you cloned this in the server root directory}

**Comment by bksahu** [comment]
@tameeshB Already done. There was some problems with Apache and I fixed it. Now my browser renders php properly. Anyway thanks for your suggestion.

**Pull request closed without merging**
