### PR TITLE
Updated Login Page UI

### PR DESCRIPTION
**Pull request by vanshsoni**
screenshot 148
Updated Login Page 
Register Page coming soon

### CODE REVIEW

**Comment by opticod** [comment]
@vanshsoni the bar below Register looks little odd, Try something different for it, rest UI looks fine.

You can try filling or something else the top section.

**Comment by opticod** [comment]
@vanshsoni the bar below `Please sign in` looks little odd, Try something different for it, rest UI looks fine.

You can try filling or something else the top section.

**Comment by vanshsoni** [comment]
screenshot 150
What about this UI?

**Review by opticod — APPROVED** [review]
Looks good! Merging!

**Comment by opticod** [comment]
This PR was for first screenshot right ? You didn't made the changes for the second screenshot here ?

**Pull request merged**
